version: '3.4'
services:
  api:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rest_api
    ports:
    - "8089:8089"
    restart: on-failure
    networks:
      - grpcapi
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: grpc_server
    ports:
    - "4040:4040"
    restart: on-failure
    networks:
      - grpcapi
  
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: otel-jaeger
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - grpcapi

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger-all-in-one
    networks:
      - grpcapi

networks:
  grpcapi:
    driver: bridge