version: '3.4'
services:
  api:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rest_api
    ports:
    - "8089:8089"
    restart: on-failure
    networks:
      - grpcapi
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: grpc_server
    ports:
    - "4040:4040"
    restart: on-failure
    networks:
      - grpcapi

networks:
  grpcapi:
    driver: bridge