apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rest_api.yaml

images:
- name: clientapi
  newName: rhiadciccoli/clientapi
  newTag: tag
- name: tag
  newName: rhiadciccoli/clientapi
  newTag: 711d7c10282a1fb20c1e78b1e4f68f0f46dd1170
