name: ci

on:
  push:
    branches:
      - 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: Rhiadc/gitops-testapi
          token: ${{ secrets.TOKEN_GITHUB }} # `GH_PAT` is a secret that contains your PAT
          ref: main

      - name: config git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
 #         git commit -am "Bump docker version"
      - name: add file
        run : |
          git checkout -b chore/bump-docker-version
          cd helmapi 
          sed 's/^\(tag: \).*$/\1'"new_tag"'/' values.yaml
          cd ..
          git add .
          git commit -m "bump docker version"
          git push -u origin chore/bump-docker-version

      